Repository microsoft/botframework-cli, pull requests merged in 2020-03, with the labels that each got.

#621 Switch to interface/implements in dialog:merge.
  libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.AdaptiveDialog.schema
  packages/dialog/src/commands/dialog/merge.ts
  packages/dialog/src/commands/dialog/readme.md
  packages/dialog/src/library/array.md
  packages/dialog/src/library/component.schema
  packages/dialog/src/library/schemaTracker.ts
  packages/dialog/test/commands/dialog/examples/app.schema
  packages/dialog/test/commands/dialog/schemas/INothing.schema
  packages/dialog/test/commands/dialog/schemas/IRecognizer.schema
  packages/dialog/test/commands/dialog/schemas/Recognizer.schema
  packages/dialog/test/commands/dialog/schemas/RecognizerTypeMismatch.schema
Labels: R8 preview

#672 Fix comparing luis applications bug in lu build
  packages/lu/src/parser/lubuild/core.ts
  packages/luis/test/fixtures/testcases/lubuild/case-insensitive/lufiles/case-insensitive.lu
  packages/luis/test/fixtures/testcases/lubuild/case-insensitive/luis/test(development)-case-insensitive.en-us.lu.json
  packages/luis/test/fixtures/testcases/lubuild/foo2/luis/test(development)-foo.en-us.lu.json
  packages/luis/test/fixtures/testcases/lubuild/foo2/luis/test(development)-foo.fr-fr.lu.json
  packages/luis/test/fixtures/testcases/lubuild/luconfig/lufiles/test.lu
  packages/luis/test/fixtures/testcases/lubuild/luconfig/luis/MyProject(development)-test.en-us.lu.json
  packages/luis/test/fixtures/testcases/lubuild/sandwich/luis/test(development)-sandwich.en-us.lu.json
  packages/luis/test/fixtures/testcases/lubuild/sandwich/luis/test(development)-sandwich.utteranceAdded.en-us.lu.json
  packages/luis/test/fixtures/testcases/lubuild/sandwich/luis/test(development)-sandwich.utteranceChanged.en-us.lu.json
Labels: R9, lu

#671 expose getActiveVersionIds function in lubuild
  packages/lu/src/parser/lubuild/builder.ts
  packages/lu/test/parser/lubuild/lubuild.test.js
Labels: R9, lu

#677 Optimize LUFileParser.g4 to accelerate parsing of simple intent section with a large number of entities
  packages/lu/src/parser/lufile/LUFileParser.g4
  packages/lu/src/parser/lufile/generated/LUFileParser.interp
  packages/lu/src/parser/lufile/generated/LUFileParser.js
  packages/lu/src/parser/lufile/generated/LUFileParserListener.js
  packages/lu/src/parser/lufile/generated/LUFileParserVisitor.js
  packages/lu/src/parser/lufile/luParser.js
Labels: lu

#612 bf luis:test implement
  packages/lu/src/parser/luis/luConverter.js
  packages/lu/src/parser/test/testhelper.ts
  packages/luis/README.md
  packages/luis/src/commands/luis/test.ts
  packages/luis/test/commands/luis/test.test.ts
  packages/luis/test/fixtures/testcases/lutest/input/AllEntity.lu
  packages/luis/test/fixtures/testcases/lutest/input/CompositeEntity.lu
  packages/luis/test/fixtures/testcases/lutest/input/EntityRole.lu
  packages/luis/test/fixtures/testcases/lutest/input/HierarchicalEntity.json
  packages/luis/test/fixtures/testcases/lutest/input/HierarchicalEntity.lu
  packages/luis/test/fixtures/testcases/lutest/input/SimpleEntity.lu
  packages/luis/test/fixtures/testcases/lutest/input/SimpleEntityRole.lu
  packages/luis/test/fixtures/testcases/lutest/input/TestFile.json
  packages/luis/test/fixtures/testcases/lutest/input/TestFile.lu
  packages/luis/test/fixtures/testcases/lutest/input/TestFile1.lu
  packages/luis/test/fixtures/testcases/lutest/input/TestFile2.lu
  packages/luis/test/fixtures/testcases/lutest/input/TestFile3.lu
  packages/luis/test/fixtures/testcases/lutest/output/AllEntity.lu
  packages/luis/test/fixtures/testcases/lutest/output/CompositeEntity.lu
  packages/luis/test/fixtures/testcases/lutest/output/EntityRole.lu
  packages/luis/test/fixtures/testcases/lutest/output/HierarchicalEntity.lu
  packages/luis/test/fixtures/testcases/lutest/output/SimpleEntity.lu
  packages/luis/test/fixtures/testcases/lutest/output/TestFile.lu
  packages/luis/test/fixtures/testcases/lutest/output/TestFile1.lu
  packages/luis/test/fixtures/testcases/lutest/output/TestFile2.lu
  packages/luis/test/fixtures/testcases/lutest/output/TestFile2_3intent.lu
  packages/luis/test/fixtures/testcases/lutest/output/TestFile2_intentOnly.lu
  specs/LUIS-TestDevSpec.md
Labels: R9
